// docs/demo/react/basics.tsx
import { useState } from "react";
import { SeamlessScroll } from "@seamless-scroll/react";

function App() {
  const [items] = useState([
    { id: 1, text: "公告1" },
    { id: 2, text: "公告2" },
    { id: 3, text: "公告3" },
  ]);

  const handleItemClick = (item: any) => {
    console.log("点击了项目:", item);
  };

  return (
    <div className="app">
      <SeamlessScroll
        data={items}
        containerHeight={200}
        duration={1000}
        forceScrolling
        onItemClick={handleItemClick}
      >
        {({ item, index }) => <div>{`${index} ${item.text}`}</div>}
      </SeamlessScroll>
    </div>
  );
}

export default App;

// docs/demo/vue/basics.vue
<script setup lang="ts">
import { ref } from "vue";
import { SeamlessScroll } from "@seamless-scroll/vue";

const items = ref([
  { id: 1, text: "公告1" },
  { id: 2, text: "公告2" },
  { id: 3, text: "公告3" },
]);

const handleItemClick = (item: any) => {
  console.log("点击了项目:", item);
};
</script>

<template>
  <div class="app">
    <SeamlessScroll
      :data="items"
      :container-height="200"
      :duration="1000"
      forceScrolling
      @item-click="handleItemClick"
    >
      <template #default="{ item, index }">
        <div>{{ `${index + 1} ${item.text}` }}</div>
      </template>
    </SeamlessScroll>
  </div>
</template>
